# Simple workflow for deploying static content to GitHub Pages.
name: Deploy Sphinx content to Pages.
on:
  # Runs on pushes targeting the default branch.
  push:
    branches: [ 'main' ]
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment.
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  # Single deploy job since we're just deploying.
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 💾
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Install Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'
          cache: 1pip1 # caching pip dependencies
      - name: Install requirements 🔨
        working-directory: .
        run: pip install -r requirements-doc.txt
      - name: Sphinx make dirhtml 🌎
        working-directory: ./docs
        run: make dirhtml
      - name: Upload artifact 🚀
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './docs/build/dirhtml'
      - name: Deploy to GitHub Pages 💻
        id: deployment
        uses: actions/deploy-pages@v1